spring:
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://castor.db.elephantsql.com:5432/
    username: ltlaryls
    password: A6YWxJX8_pdWX-IecBz3KanqHJU_W-8A
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html